export const tyilFellowsLists = [
  // 2019 Alumni Fellows
  {
    id: 1,
    name: "Titilayo Adegboye",
    role: "View Profile",
    image: "/fellows/titilayo_adegboye.jpg",
    profileUrl: "https://www.linkedin.com/in/titilayoadegboye/",
    year: 2019,
  },
  {
    id: 2,
    name: "Ben-eze David",
    role: "View Profile",
    image: "/fellows/ben-eze_chidiebere.jpg",
    profileUrl: "https://www.linkedin.com/in/ben-eze-chidiebere-d/",
    year: 2019,
  },
  {
    id: 3,
    name: "Ibuoye Precious",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/precious-ibuoye-a33b5320a/",
    year: 2019,
  },
  {
    id: 4,
    name: "Oluwatobi Agboola",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/oluwatobi-agboola-78a959289/",
    year: 2019,
  },
  {
    id: 5,
    name: "Oluwatoyin Akinwunmi",
    role: "",
    image: "",
    profileUrl: "",
    year: 2019,
  },
  {
    id: 6,
    name: "Blessing Mokwenye",
    role: "View Profile",
    image: "/fellows/blessing_mokwenye.jpeg",
    profileUrl:
      "https://www.linkedin.com/in/theintentionalladyfortransfomationblessing-mokwenye-6b003511b/",
    year: 2019,
  },
  {
    id: 7,
    name: "Akingbade Maria",
    role: "View Profile",
    image: "/fellows/maria_akingbade.jpg",
    profileUrl:
      "https://www.linkedin.com/in/maria-anuoluwapo-akingbade-b62113230/",
    year: 2019,
  },
  {
    id: 8,
    name: "Goodness Emeka",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/emeka-goodness-b90388226/",
    year: 2019,
  },
  {
    id: 9,
    name: "Chukwuka Austine",
    role: "View Profile",
    image: "/fellows/chuks_austine.jpg",
    profileUrl: "https://www.linkedin.com/in/chuksaustine/",
    year: 2019,
  },
  {
    id: 10,
    name: "Patience Ogunremi",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/patienceogunremi/",
    year: 2019,
  },

  // 2020 Alumni Fellows
  {
    id: 11,
    name: "Afolabi Adeniyi",
    role: "",
    image: "",
    profileUrl: "",
    year: 2020,
  },
  {
    id: 12,
    name: "Unimashi Ugbe",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/unimashi-ugbe-9a1ba8248/",
    year: 2020,
  },
  {
    id: 13,
    name: "Susana Oladipo",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/susana-oladipo-ba2b65240/",
    year: 2020,
  },
  {
    id: 14,
    name: "Flourish Agbolade",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/flourishagbolade/",
    year: 2020,
  },
  {
    id: 15,
    name: "Ruth Ogieva",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/ruth-ogieva/",
    year: 2020,
  },
  {
    id: 16,
    name: "Adedigba Adejoke",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/adejoke-adedigba-746a32240/",
    year: 2020,
  },
  {
    id: 17,
    name: "Agosu Seide",
    role: "View Profile",
    image: "/fellows/aseide_agosu.jpg",
    profileUrl: "https://www.linkedin.com/in/thesmartseide/",
    year: 2020,
  },
  {
    id: 18,
    name: "Olayinka-Popoola Oyinkansola",
    role: "",
    image: "",
    profileUrl: "",
    year: 2020,
  },
  {
    id: 19,
    name: "Fatogun Monisola",
    role: "View Profile",
    image: "",
    profileUrl:
      "https://www.linkedin.com/in/fatogun-monisola-omodolapo-0abb26173/",
    year: 2020,
  },
  {
    id: 20,
    name: "Adekola Gbolagade",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/adekolagbolagade/",
    year: 2020,
  },
  {
    id: 21,
    name: "Ezoiribhor Godsave",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/godsaveezoiribhor/",
    year: 2020,
  },
  {
    id: 22,
    name: "Nwanne Onuoha",
    role: "",
    image: "",
    profileUrl: "",
    year: 2020,
  },
  {
    id: 23,
    name: "John Ijato",
    role: "",
    image: "",
    profileUrl: "",
    year: 2020,
  },
  {
    id: 24,
    name: "Maranatha Aina",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/maranatha-aina/",
    year: 2020,
  },
  {
    id: 25,
    name: "Olusegun Orukotan",
    role: "",
    image: "",
    profileUrl: "",
    year: 2020,
  },
  {
    id: 26,
    name: "Victor Otokpa",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/victor-otokpa-268a081a9/",
    year: 2020,
  },
  {
    id: 27,
    name: "Afolayan Iyanuoluwa",
    role: "",
    image: "",
    profileUrl: "",
    year: 2020,
  },
  {
    id: 28,
    name: "Olakunle Odagbodo",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/olakunle-odagbodo-803166163/",
    year: 2020,
  },
  {
    id: 29,
    name: "Chukwu Ijeoma",
    role: "",
    image: "",
    profileUrl: "",
    year: 2020,
  },

  // 2022 Alumni Fellows
  {
    id: 30,
    name: "Theophilus Olaleye",
    role: "View Profile",
    image: "",
    profileUrl: "",
    year: 2022,
  },
  {
    id: 31,
    name: "Apara Jesutomisin",
    role: "View Profile",
    image: "",
    profileUrl: "",
    year: 2022,
  },
  {
    id: 32,
    name: "Wakeel Olusewa",
    role: "View Profile",
    image: "",
    profileUrl: "",
    year: 2022,
  },
  {
    id: 33,
    name: "Oluwabunmi Akinleminu",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/oluwabunmi-akinleminu-ab7b902a1/",
    year: 2022,
  },
  {
    id: 34,
    name: "Amos Oroshi",
    role: "View Profile",
    image: "/fellows/deborah_amos.jpg",
    profileUrl: "https://www.linkedin.com/in/amos-deborah/",
    year: 2022,
  },
  {
    id: 35,
    name: "Emmanuel Arowesan",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/emmanuel-arowesan/",
    year: 2022,
  },
  {
    id: 36,
    name: "Adedayo Mary",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/mary-nkechi-adedayo-528a7920b/",
    year: 2022,
  },
  {
    id: 37,
    name: "Franklin Nwaribe",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/franklin-nwaribe-6178101a5/",
    year: 2022,
  },
  {
    id: 38,
    name: "Damilola Tooki",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/damilola-tooki/",
    year: 2022,
  },
  {
    id: 39,
    name: "Tolulope Ogunniyi",
    role: "View Profile",
    image: "/fellows/oguniyi_tolulope.jpg",
    profileUrl: "https://www.linkedin.com/in/tolulope-ogunniyi-26b5861b9/",
    year: 2022,
  },
  {
    id: 40,
    name: "Gbemisola Oloro",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/gbemisolaoloro/",
    year: 2022,
  },
  {
    id: 41,
    name: "Ibuoye Blessing",
    role: "View Profile",
    image: "",
    profileUrl: "",
    year: 2022,
  },
  {
    id: 42,
    name: "Confidence Ubani",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/confidence-n-ubani/",
    year: 2022,
  },

  // 2023 Alumni Fellows
  {
    id: 43,
    name: "Oguntoyinbo Opeoluwa",
    role: "View Profile",
    image: "/fellows/opeoluwa_oguntoyinbo.HEIC",
    profileUrl: "https://www.linkedin.com/in/opeoluwa-oguntoyinbo/",
    year: 2023,
  },
  {
    id: 44,
    name: "Agbaje Abdullahi",
    role: "View Profile",
    image: "/fellows/agbaje_abdullahi.png",
    profileUrl:
      "https://www.linkedin.com/in/abdullahi-adewale-agbaje-a3698a1a4/",
    year: 2023,
  },
  {
    id: 45,
    name: "Emaye Oluwafemi",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/oluwafemi-emaye/",
    year: 2023,
  },
  {
    id: 46,
    name: "Millenium Anthony",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/millenium-anthony/",
    year: 2023,
  },
  {
    id: 47,
    name: "Opeoluwa Adejumo",
    role: "View Profile",
    image: "",
    profileUrl: "",
    year: 2023,
  },
  {
    id: 48,
    name: "Olatunde Marvellous",
    role: "View Profile",
    image: "/fellows/olatunde _marvellous.jpg",
    profileUrl:
      "https://www.linkedin.com/in/marvellous-olatunde-aicmc-91245919b/",
    year: 2023,
  },
  {
    id: 49,
    name: "Israel Adeniyi",
    role: "View Profile",
    image: "",
    profileUrl:
      "https://www.linkedin.com/in/israel-adekunle-adeniyi-b7b9671b7/",
    year: 2023,
  },
  {
    id: 50,
    name: "Adeyemi Samuel",
    role: "View Profile",
    image: "",
    profileUrl: "",
    year: 2023,
  },
  {
    id: 51,
    name: "Adenike Oladimeji",
    role: "View Profile",
    image: "/fellows/adenike_oladimeji.jpg",
    profileUrl: "https://www.linkedin.com/in/adenike-oladimeji-33508a248/",
    year: 2023,
  },
  {
    id: 52,
    name: "Oyinkansola Abisoye",
    role: "View Profile",
    image: "/fellows/oyinkansola_abisoye.jpeg",
    profileUrl: "https://www.linkedin.com/in/oyinkansola-abisoye-0976aa247/",
    year: 2023,
  },
  {
    id: 53,
    name: "Sodiq Safiriyu",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/sodiqsafiriyu/",
    year: 2023,
  },
  {
    id: 54,
    name: "Onyeka Ugo",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/onyeka-collins-ugo/",
    year: 2023,
  },
  {
    id: 55,
    name: "Zakariya’u Dauda",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/zakariya-u-dauda/",
    year: 2023,
  },
  {
    id: 56,
    name: "Oluwatobiloba Popoola",
    role: "View Profile",
    image: "/fellows/aoluwatobiloba_popoola.png",
    profileUrl: "https://www.linkedin.com/in/oluwatobiloba-popoola-7647b421b/",
    year: 2023,
  },
  {
    id: 57,
    name: "Sanusi Masudat",
    role: "View Profile",
    image: "",
    profileUrl: "",
    year: 2023,
  },
  {
    id: 58,
    name: "Eloka Annabel",
    role: "View Profle",
    image: "/fellows/annabel_eloka.jpg",
    profileUrl: "",
    year: 2023,
  },
  {
    id: 59,
    name: "Ogunyade Bolaji",
    role: "View Profle",
    image: "",
    profileUrl: "https://www.linkedin.com/in/bolaji-ogunyade/",
    year: 2023,
  },
  {
    id: 60,
    name: "Ogunyade Bolaji",
    role: "View Profle",
    image: "",
    profileUrl: "https://www.linkedin.com/in/bolaji-ogunyade/",
    year: 2023,
  },
  {
    id: 61,
    name: "Ojo Emmanuel",
    role: "View Profle",
    image: "",
    profileUrl: "https://www.linkedin.com/in/ojoe1/",
    year: 2023,
  },
  {
    id: 62,
    name: "Adetoun Adewoyin",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/ojoe1/",
    year: 2023,
  },
  {
    id: 63,
    name: "Tewogbade Olawale",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/tewogbade-olawale-7a91b4270/",
    year: 2023,
  },
  {
    id: 64,
    name: "Ruqoyah Alata",
    role: "View Profile",
    image: "",
    profileUrl: "https://www.linkedin.com/in/ruqoyah-alata-86374b240/",
    year: 2023,
  },
  {
    id: 65,
    name: "Dada Oluwafeyisara",
    role: "",
    image: "",
    profileUrl: "",
    year: 2023,
  },
  {
    id: 66,
    name: "Dawud Hawwau",
    role: "View Profile",
    image: "/fellows/dawud_hawwau.jpeg",
    profileUrl: "https://www.linkedin.com/in/dawud-hawwau-olayimika-4a425824a/",
    year: 2023,
  },
  {
    id: 67,
    name: "Opeyemi Ojo",
    role: "",
    image: "",
    profileUrl: "",
    year: 2023,
  },

  // 2024 Alumni Fellows
  {
    id: 68,
    name: "Salau Ismail",
    role: "",
    image: "",
    profileUrl: "",
    year: 2024,
  },
  {
    id: 69,
    name: "Adebowale Hiqmat",
    role: "",
    image: "",
    profileUrl: "",
    year: 2024,
  },
  {
    id: 70,
    name: "Abdullahi Saminu",
    role: "",
    image: "/fellows/abdullahi_saminu.jpg",
    profileUrl: "",
    year: 2024,
  },
  {
    id: 71,
    name: "Omogiate Deborah",
    role: "",
    image: "/fellows/deborah_omogiate.jpg",
    profileUrl: "",
    year: 2024,
  },
  {
    id: 72,
    name: "Adejumola Folashade",
    role: "",
    image: "/fellows/folashade_adejumola.webp",
    profileUrl: "",
    year: 2024,
  },
  {
    id: 73,
    name: "Kayukiro Gloria",
    role: "",
    image: "/fellows/kayukiro_gloria.jpg",
    profileUrl: "",
    year: 2024,
  },
  {
    id: 74,
    name: "Afolabi Dorcas",
    role: "",
    image: "",
    profileUrl: "",
    year: 2024,
  },
  {
    id: 75,
    name: "Achu Cecilia",
    role: "",
    image: "/fellows/achu_cecilia.jpg",
    profileUrl: "",
    year: 2024,
  },
  {
    id: 76,
    name: "Martin Kiptoo",
    role: "",
    image: "",
    profileUrl: "",
    year: 2024,
  },
  {
    id: 77,
    name: "Babatunde Toyibat",
    role: "",
    image: "/fellows/babatunde_toyibat.jpg",
    profileUrl: "",
    year: 2024,
  },
  {
    id: 78,
    name: "AbdusSalam Ummul-Khayr",
    role: "",
    image: "",
    profileUrl: "",
    year: 2024,
  },
  {
    id: 79,
    name: "Happiness Daniel",
    role: "",
    image: "",
    profileUrl: "",
    year: 2024,
  },
  {
    id: 80,
    name: "Qamarudeen Fahidat",
    role: "",
    image: "/fellows/fahidat_qamarudeen.jpg",
    profileUrl: "",
    year: 2024,
  },
  {
    id: 81,
    name: "Ayodeji Ojekemi",
    role: "",
    image: "/fellows/ojekemi_ayodeji.JPG",
    profileUrl: "",
    year: 2024,
  },
  {
    id: 82,
    name: "Heritage Akinola",
    role: "",
    image: "",
    profileUrl: "",
    year: 2024,
  },
  {
    id: 83,
    name: "Julius Obukohwo",
    role: "",
    image: "",
    profileUrl: "",
    year: 2024,
  },

  // 2025 Alumni fellows
  {
    id: 84,
    name: "Balogun Praise",
    role: "",
    image: "",
    profileUrl: "",
    year: 2025,
  },
  {
    id: 85,
    name: "Progress Okandeji",
    role: "",
    image: "/fellows/okandeji_progress.png",
    profileUrl: "",
    year: 2025,
  },
  {
    id: 86,
    name: "Rukayat Ajoke",
    role: "",
    image: "",
    profileUrl: "",
    year: 2025,
  },
  {
    id: 87,
    name: "Faruq Gbolahan",
    role: "",
    image: "",
    profileUrl: "",
    year: 2025,
  },
  {
    id: 88,
    name: "Rafiu",
    role: "",
    image: "",
    profileUrl: "",
    year: 2025,
  },
  {
    id: 89,
    name: "Jesutofunmi Osin",
    role: "",
    image: "/fellows/jesutofunmi_osin.jpeg",
    profileUrl: "",
    year: 2025,
  },
  {
    id: 90,
    name: "Abigail Fasanmi",
    role: "",
    image: "/fellows/abigail_fasanmi.jpeg",
    profileUrl: "",
    year: 2025,
  },
] as const;

export type tyilFellows = (typeof tyilFellowsLists)[number];
